image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - java -jar ./artifacts/app-order.jar &

build_script:
  - chmod 755 ./driver/chromedriver_linux64/chromedriver
  - chmod +x gradlew
  - chmod +x driver/chromedriver_linux64/chromedriver
  - ./gradlew test --info